spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timviec?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: hozonew123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 801476171386686
            clientSecret: 7372287ea3c01ed44c2e68e466af8067
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,last_name,name,email,picture.width(250).height(250)
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: trungdang82678@gmail.com
    password: ebyzmfinztoqladf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
file:
  uploadDir: /hdd/data/photographer/upload/
  tempExportExcel: /hdd/data/photographer/tmp/
  libreOfficePath: /hdd/setup/libreoffice/opt/libreoffice6.4/program/
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
